spring:
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: spring_mail_username
    password: spring_mail_password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: "*"