package com.traintogain.backend.exercise;

public enum BasePatternRegistry {

    VERTICAL_PUSH,
    HORIZONTAL_PUSH,
    INCLINE_PUSH,
    DECLINE_PUSH,

    VERTICAL_PULL,
    HORIZONTAL_PULL,

    SQUAT_PATTERN,
    HINGE_PATTERN,
    LUNGE_PATTERN,

    ANTI_EXTENSION,
    ANTI_ROTATION,
    ANTI_LATERAL_FLEXION,

    ELBOW_FLEXION,
    ELBOW_EXTENSION,
    LATERAL_RAISE,
    FRONT_RAISE,

    CYCLING,
    GAIT,
    CARRY,

    SPINAL_ROTATION,
    SPINAL_FLEXION,

    CYCLICAL_JUMP
}