package com.traintogain.backend.exercise;

public enum BasePatternRegistry {
    HORIZONTAL_PUSH,
    VERTICAL_PUSH,
    INCLINE_PUSH,
    DECLINE_PUSH,

    HORIZONTAL_PULL,
    VERTICAL_PULL,

    HIP_HINGE,
    HIP_EXTENSION,  // <-- neu hinzufügen
    LUNGE_PATTERN,
    SQUAT_PATTERN,
    STEP_UP,
    CARRY,
    ISOLATION_CARRY,
    CONDITIONING,

    ANTI_EXTENSION,
    ELBOW_EXTENSION,
    ELBOW_FLEXION,
    FRONT_RAISE,
    REAR_DELT_FLY,
    LATERAL_RAISE,
    SHRUG,
    SPINAL_FLEXION,
    SPINAL_ROTATION,
    ANTI_ROTATION,
    ANTI_LATERAL_FLEXION,
    GAIT,

    HORIZONTAL_ADDUCTION,
    HORIZONTAL_ABDUCTION,
    SCAPULAR_ELEVATION,
    KNEE_FLEXION
}