package com.traintogain.backend.exercise;

public enum BasePatternRegistry {

    HORIZONTAL_PUSH,
    INCLINE_PUSH,
    DECLINE_PUSH,
    VERTICAL_PUSH,

    HORIZONTAL_PULL,
    VERTICAL_PULL,

    HIP_HINGE,
    SQUAT_PATTERN,

    LATERAL_RAISE,
    FRONT_RAISE,

    SPINAL_FLEXION,
    SPINAL_FLEXION_FULL,

    SPINAL_ROTATION,

    ANTI_EXTENSION,
    ANTI_LATERAL_FLEXION,

    CARRY,
    GAIT_PATTERN,

    SCAPULAR_RETRACTION,
    ELBOW_FLEXION,
    ELBOW_EXTENSION,
    ELBOW_EXTENSION_OVERHEAD,

    CYCLING,
    WAVE_PATTERN,
    FORCE_DRIVE,
    CYCLICAL_JUMP,

    FULL_BODY_COMPOUND
}