package com.traintogain.backend.exercise;

public enum FamilyRegistry {

    CHEST_PRESS_FAMILY,
    INCLINE_PRESS_FAMILY,
    DECLINE_PRESS_FAMILY,

    ROW_THICKNESS_FAMILY,
    LAT_FAMILY,

    DEADLIFT_FAMILY,
    HINGE_SUPPORT_FAMILY,

    SQUAT_FAMILY,
    MACHINE_SQUAT_FAMILY,
    UNILATERAL_SQUAT_FAMILY,

    BICEPS_CURL_FAMILY,
    TRICEPS_EXTENSION_FAMILY,

    SHOULDER_PRESS_FAMILY,
    LATERAL_RAISE_FAMILY,
    REAR_DELTA_FAMILY,

    CORE_STABILITY_FAMILY,
    CORE_ROTATION_FAMILY,
    CORE_ADVANCED_FAMILY,

    CABLE_CHEST_FAMILY,
    FLIGHT_FAMILY,

    FOREARM_GRIP_FAMILY,

    FULL_BODY_CONDITIONING_FAMILY,
    CARDIO_FAMILY
}