package com.traintogain.backend.catalog.model;

public enum Muscle {
    PECTORALIS_MAJOR,
    PECTORALIS_MINOR,
    LATISSIMUS_DORSI,
    TRAPEZIUS,
    ERECTOR_SPINAE,
    DELTOID_ANTERIOR,
    DELTOID_LATERAL,
    DELTOID_POSTERIOR,
    BICEPS_BRACHII,
    TRICEPS_BRACHII,
    FOREARMS,
    BRACHIALIS,
    RECTUS_ABDOMINIS,
    OBLIQUES,
    ILIOPSOAS,
    QUADRICEPS,
    HAMSTRINGS,
    GLUTEUS_MAXIMUS,
    GLUTEUS_MEDIUS,
    CALVES
}